"""App Generator — produces real, runnable files from an AppSpec."""

from __future__ import annotations

from pathlib import Path

from .models import AppSpec, AppType, GeneratedFile


class AppGenerator:
    """Generate complete runnable app files from a specification."""

    def generate(self, spec: AppSpec) -> list[GeneratedFile]:
        files: list[GeneratedFile] = []

        if spec.app_type == AppType.API_BACKEND:
            files.extend(self._backend_files(spec))
        elif spec.app_type == AppType.FULLSTACK:
            files.extend(self._backend_files(spec))
            files.extend(self._frontend_files(spec))
        elif spec.app_type == AppType.CLI_TOOL:
            files.extend(self._cli_files(spec))

        # Common files
        files.extend(self._common_files(spec))
        return files

    # -----------------------------------------------------------
    # Backend
    # -----------------------------------------------------------

    def _backend_files(self, spec: AppSpec) -> list[GeneratedFile]:
        return [
            GeneratedFile("main.py", self._render_main(spec), is_executable=True),
            GeneratedFile("models.py", self._render_models(spec)),
            GeneratedFile("database.py", self._render_database(spec)),
            GeneratedFile("seed_data.py", self._render_seed(spec)),
            GeneratedFile("requirements.txt", self._render_requirements()),
        ]

    def _render_main(self, spec: AppSpec) -> str:
        entity_names = [e.lower().replace(" ", "_") for e in spec.entities]
        routes = "\n".join(self._route_block(e) for e in entity_names)
        return f'''"""FastAPI backend for {spec.app_name} — generated by OMNIS App Factory."""
from fastapi import FastAPI, HTTPException
from database import init_db, get_db
from models import {", ".join(entity_names) if entity_names else "Base"}

app = FastAPI(title="{spec.app_name}", description="{spec.description}")


@app.on_event("startup")
def startup():
    init_db()


@app.get("/health")
def health():
    return {{"status": "ok", "app": "{spec.app_name}"}}

{routes}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port={spec.port})
'''

    def _route_block(self, entity: str) -> str:
        return f'''
@app.get("/{entity}s")
def list_{entity}s():
    return get_db().get_all("{entity}s")


@app.post("/{entity}s")
def create_{entity}(data: dict):
    return get_db().insert("{entity}s", data)


@app.get("/{entity}s/{{item_id}}")
def get_{entity}(item_id: int):
    item = get_db().get_by_id("{entity}s", item_id)
    if not item:
        raise HTTPException(status_code=404)
    return item
'''

    def _render_models(self, spec: AppSpec) -> str:
        entities_code = []
        for e in spec.entities:
            name = e.lower().replace(" ", "_")
            entities_code.append(f'''
class {name.title().replace("_", "")}(Base):
    __tablename__ = "{name}s"
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    description = Column(Text, default="")
    created_at = Column(DateTime, default=datetime.utcnow)
''')
        return f'''"""SQLAlchemy models for {spec.app_name}."""
from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, DateTime, create_engine
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
{chr(10).join(entities_code) if entities_code else "# No entities defined"}
'''

    def _render_database(self, spec: AppSpec) -> str:
        return f'''"""SQLite database layer for {spec.app_name}."""
import json
from pathlib import Path
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from models import Base

DB_PATH = Path("{spec.app_name}.db")
_engine = None
_Session = None


def get_engine():
    global _engine
    if _engine is None:
        _engine = create_engine(f"sqlite:///{{DB_PATH}}", echo=False)
    return _engine


def get_session():
    global _Session
    if _Session is None:
        _Session = sessionmaker(bind=get_engine())
    return _Session()


def init_db():
    Base.metadata.create_all(get_engine())


class JSONLStore:
    """Simple JSONL-backed data store (no SQLAlchemy dependency)."""

    def __init__(self, filepath: str):
        self.path = Path(filepath)

    def get_all(self, collection: str) -> list[dict]:
        if not self.path.exists():
            return []
        return [json.loads(line) for line in self.path.read_text(encoding="utf-8").splitlines() if line.strip()]

    def insert(self, collection: str, data: dict) -> dict:
        import uuid
        data["id"] = data.get("id", uuid.uuid4().hex[:8])
        with open(self.path, "a", encoding="utf-8") as f:
            f.write(json.dumps(data, ensure_ascii=False) + "\\n")
        return data

    def get_by_id(self, collection: str, item_id) -> dict | None:
        for item in self.get_all(collection):
            if item.get("id") == item_id:
                return item
        return None


_db_store: JSONLStore | None = None


def get_db() -> JSONLStore:
    global _db_store
    if _db_store is None:
        _db_store = JSONLStore("{spec.app_name}_data.jsonl")
    return _db_store
'''

    def _render_seed(self, spec: AppSpec) -> str:
        seed_items = []
        for i, e in enumerate(spec.entities, 1):
            seed_items.append(f'    db.insert("{e.lower().replace(" ", "_")}s", {{"name": "{e} Exemplo {i}", "description": "Seed data para {e}"}})')
        seed_code = "\n".join(seed_items) if seed_items else "    pass"
        return f'''"""Seed data for {spec.app_name}."""
from database import get_db, init_db

def seed():
    init_db()
    db = get_db()
{seed_code}
    print("Seed data inserted.")

if __name__ == "__main__":
    seed()
'''

    def _render_requirements(self) -> str:
        return "fastapi\nuvicorn\nsqlalchemy\n"

    # -----------------------------------------------------------
    # Frontend
    # -----------------------------------------------------------

    def _frontend_files(self, spec: AppSpec) -> list[GeneratedFile]:
        return [
            GeneratedFile("frontend/index.html", self._render_index_html(spec)),
            GeneratedFile("frontend/app.js", self._render_app_js(spec)),
        ]

    def _render_index_html(self, spec: AppSpec) -> str:
        return f'''<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{spec.app_name}</title>
    <style>
        body{{font-family:system-ui,sans-serif;max-width:800px;margin:40px auto;padding:0 20px;background:#f5f5f5}}
        h1{{color:#e76f00}} .card{{background:#fff;border-radius:8px;padding:16px;margin:12px 0;box-shadow:0 2px 4px rgba(0,0,0,.1)}}
    </style>
</head>
<body>
    <h1>{spec.app_name}</h1>
    <p>{spec.description}</p>
    <div id="app"></div>
    <script src="app.js"></script>
</body>
</html>'''

    def _render_app_js(self, spec: AppSpec) -> str:
        entities_json = str([e.lower().replace(" ", "_") for e in spec.entities])
        return f'''// Frontend app for {spec.app_name}
const API = "http://localhost:{spec.port}";
const entities = {entities_json};

async function loadData() {{
    const app = document.getElementById("app");
    for (const entity of entities) {{
        try {{
            const res = await fetch(`${{API}}/${{entity}}s`);
            const items = await res.json();
            app.innerHTML += `<div class="card"><h2>${{entity}}s</h2><pre>${{JSON.stringify(items, null, 2)}}</pre></div>`;
        }} catch (e) {{
            app.innerHTML += `<div class="card" style="color:red">Erro carregando ${{entity}}s: ${{e.message}}</div>`;
        }}
    }}
}}

loadData();
'''

    # -----------------------------------------------------------
    # CLI
    # -----------------------------------------------------------

    def _cli_files(self, spec: AppSpec) -> list[GeneratedFile]:
        return [
            GeneratedFile("cli.py", self._render_cli(spec), is_executable=True),
            GeneratedFile("requirements.txt", GeneratedFile("","").content if False else "typer\n"),
        ]

    def _render_cli(self, spec: AppSpec) -> str:
        commands = "\n".join(
            f'@app.command()\ndef {e.lower().replace(" ", "_")}(): \n    print("Executando: {e}")'
            for e in spec.entities
        ) if spec.entities else '@app.command()\ndef hello():\n    print("Hello from {spec.app_name}!")'

        return f'''"""CLI tool: {spec.app_name} — generated by OMNIS."""
import typer

app = typer.Typer(help="{spec.description}")

{commands}

if __name__ == "__main__":
    app()
'''

    # -----------------------------------------------------------
    # Common
    # -----------------------------------------------------------

    def _common_files(self, spec: AppSpec) -> list[GeneratedFile]:
        return [
            GeneratedFile("README.md", self._render_readme(spec)),
            GeneratedFile("tests/test_app.py", self._render_tests(spec)),
        ]

    def _render_readme(self, spec: AppSpec) -> str:
        return f'''# {spec.app_name}

{spec.description}

**Gerado por OMNIS App Factory Executable** — {spec.app_type.value}

## Instalacao

```bash
pip install -r requirements.txt
```

## Executar

```bash
# API Backend
python main.py

# CLI Tool
python cli.py --help

# Fullstack
python main.py  # backend
# Abrir frontend/index.html no navegador
```

## Banco de Dados

SQLite local: `{spec.app_name}.db`

## Seed Data

```bash
python seed_data.py
```

## Testes

```bash
python -m pytest tests/ -v
```

## Estrutura

```
.
├── main.py          # Backend API (FastAPI)
├── models.py        # SQLAlchemy models
├── database.py      # SQLite connection
├── seed_data.py     # Seed data script
├── frontend/        # Frontend SPA
│   ├── index.html
│   └── app.js
├── tests/           # Test suite
│   └── test_app.py
├── requirements.txt # Python dependencies
└── README.md        # This file
```
'''

    def _render_tests(self, spec: AppSpec) -> str:
        return f'''"""Tests for {spec.app_name}."""
import pytest
from fastapi.testclient import TestClient
from main import app

client = TestClient(app)


def test_health():
    response = client.get("/health")
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "ok"
    assert data["app"] == "{spec.app_name}"


def test_openapi_schema():
    response = client.get("/openapi.json")
    assert response.status_code == 200


@pytest.mark.parametrize("endpoint", [
    {", ".join(f'"/{e.lower().replace(" ", "_")}s"' for e in spec.entities) if spec.entities else '"/health"'},
])
def test_endpoints_exist(endpoint):
    response = client.get(endpoint)
    assert response.status_code in (200, 404)
'''
