"""P26 AppPackager — packages build into final deliverable."""
from __future__ import annotations

from pathlib import Path

from src.app_factory_supreme.models import AppBuild


class AppPackager:
    """Packages an AppBuild into a final output directory with README, etc."""

    def __init__(self, dry_run: bool = True) -> None:
        self.dry_run = dry_run

    def package(self, build: AppBuild) -> AppBuild:
        """Package the build for delivery."""
        if self.dry_run:
            build.output_dir = str(Path("generated_apps") / "dry_run" / build.build_id)
            return build

        build.output_dir = str(Path("generated_apps") / build.build_id)
        return build

    def generate_readme(self, build: AppBuild) -> str:
        """Generate README.md for the packaged app."""
        lines = [
            f"# {build.title or 'Generated App'}",
            "",
            f"Generated by OMNIS P26 App Factory Supreme (Build: {build.build_id})",
            "",
            "## Modules",
        ]
        for m in build.modules:
            status = "✓" if m.tests_pass else "✗"
            lines.append(f"- [{status}] {m.module_name} ({m.test_count} tests)")
        return "\n".join(lines)

    def generate_dockerfile(self, build: AppBuild) -> str:
        """Generate Dockerfile for the app."""
        return (
            "FROM python:3.11-slim\n"
            "WORKDIR /app\n"
            "COPY . .\n"
            'CMD ["python", "-m", "pytest"]\n'
        )
