"""P4 Memory Pack / Akasha Bridge — dry-run memory context and writeback planning."""
from src.memory_pack.models import (
    MemorySource,
    MemoryQuery,
    MemoryHit,
    ContextPack,
    MissionMemoryRecord,
    MemoryWritePlan,
    MemorySourceType,
    SOURCE_AKASHA,
    SOURCE_OBSIDIAN,
    SOURCE_MEM0,
    SOURCE_GRINGOTTS,
    SOURCE_BIBLIOTECA,
    SOURCE_SESSION,
    SOURCE_STATIC,
    VALID_SOURCES,
    VALID_SECTORS,
    VALID_RELEVANCES,
    VALID_FORMATS,
    VALID_WRITE_ACTIONS,
    VALID_RECORD_STATUSES,
    RELEVANCE_RANK,
    RELEVANCE_EXACT,
    RELEVANCE_HIGH,
    RELEVANCE_MEDIUM,
    RELEVANCE_LOW,
    RELEVANCE_NONE,
    FORMAT_JSON,
    FORMAT_MARKDOWN,
    FORMAT_DICT,
    ACTION_INSERT,
    ACTION_UPDATE,
    ACTION_UPSERT,
    ACTION_DELETE,
    STATUS_DRAFT,
    STATUS_ACTIVE,
    STATUS_ARCHIVED,
    STATUS_SUPERSEDED,
    SECTOR_MIDIA,
    SECTOR_COMERCIAL,
    SECTOR_VENDAS,
    SECTOR_CONHECIMENTO,
    SECTOR_PRODUTO,
    SECTOR_FINANCEIRO,
    SECTOR_OPERACOES,
)
from src.memory_pack.service import (
    MemoryPackPlanner,
    validate_memory_query,
    rank_memory_hits,
    build_context_pack,
    plan_memory_writeback,
    export_context_pack,
)
from src.memory_pack.errors import (
    MemoryPackError,
    QueryValidationError,
    EmptyQueryError,
    InvalidSourceError,
    InvalidSectorError,
    ContextPackError,
    EmptyHitListError,
    RankingError,
    WritePlanError,
    DestructiveActionBlockedError,
    WritebackBlockedError,
    AkashaConnectionProhibitedError,
    ExportError,
    InvalidFormatError,
    SerializationError,
)

__all__ = [
    # Models
    "MemorySource",
    "MemoryQuery",
    "MemoryHit",
    "ContextPack",
    "MissionMemoryRecord",
    "MemoryWritePlan",
    "MemorySourceType",
    # Source constants
    "SOURCE_AKASHA",
    "SOURCE_OBSIDIAN",
    "SOURCE_MEM0",
    "SOURCE_GRINGOTTS",
    "SOURCE_BIBLIOTECA",
    "SOURCE_SESSION",
    "SOURCE_STATIC",
    "VALID_SOURCES",
    # Sector constants
    "VALID_SECTORS",
    "SECTOR_MIDIA",
    "SECTOR_COMERCIAL",
    "SECTOR_VENDAS",
    "SECTOR_CONHECIMENTO",
    "SECTOR_PRODUTO",
    "SECTOR_FINANCEIRO",
    "SECTOR_OPERACOES",
    # Relevance constants
    "VALID_RELEVANCES",
    "RELEVANCE_RANK",
    "RELEVANCE_EXACT",
    "RELEVANCE_HIGH",
    "RELEVANCE_MEDIUM",
    "RELEVANCE_LOW",
    "RELEVANCE_NONE",
    # Format constants
    "VALID_FORMATS",
    "FORMAT_JSON",
    "FORMAT_MARKDOWN",
    "FORMAT_DICT",
    # Action constants
    "VALID_WRITE_ACTIONS",
    "ACTION_INSERT",
    "ACTION_UPDATE",
    "ACTION_UPSERT",
    "ACTION_DELETE",
    # Status constants
    "VALID_RECORD_STATUSES",
    "STATUS_DRAFT",
    "STATUS_ACTIVE",
    "STATUS_ARCHIVED",
    "STATUS_SUPERSEDED",
    # Service
    "MemoryPackPlanner",
    "validate_memory_query",
    "rank_memory_hits",
    "build_context_pack",
    "plan_memory_writeback",
    "export_context_pack",
    # Errors
    "MemoryPackError",
    "QueryValidationError",
    "EmptyQueryError",
    "InvalidSourceError",
    "InvalidSectorError",
    "ContextPackError",
    "EmptyHitListError",
    "RankingError",
    "WritePlanError",
    "DestructiveActionBlockedError",
    "WritebackBlockedError",
    "AkashaConnectionProhibitedError",
    "ExportError",
    "InvalidFormatError",
    "SerializationError",
]
