"""P15 Computer Ops Read-Only — auditoria, classificacao e planos de limpeza segura."""

from src.computer_ops.models import (
    AuditTarget,
    DiskFinding,
    ProjectFinding,
    DockerFinding,
    CleanupCandidate,
    ComputerOpsReport,
    TARGET_DISK,
    TARGET_PROJECT,
    TARGET_DOCKER,
    TARGET_SYSTEM,
    SEVERITY_LOW,
    SEVERITY_MEDIUM,
    SEVERITY_HIGH,
    SEVERITY_CRITICAL,
    ACTION_QUARANTINE,
    ACTION_ARCHIVE,
    ACTION_DELETE,
    ACTION_KEEP,
    ACTION_REVIEW,
    SAFE_ACTIONS,
    DESTRUCTIVE_ACTIONS,
    STATUS_IDENTIFIED,
    STATUS_CLASSIFIED,
    STATUS_QUARANTINED,
    REPORT_DRAFT,
    REPORT_FINAL,
    REPORT_ARCHIVED,
    VALID_TARGETS,
    VALID_SEVERITIES,
    VALID_ACTIONS,
    VALID_STATUSES,
    VALID_REPORT_STATUSES,
)
from src.computer_ops.service import (
    ComputerOpsPlanner,
    AuditPlan,
    ClassificationResult,
    SafeCleanupPlan,
    build_readonly_audit_plan,
    classify_cleanup_candidate,
    generate_safe_cleanup_plan,
)
from src.computer_ops.errors import (
    ComputerOpsError,
    AuditPlanError,
    EmptyTargetListError,
    InvalidTargetTypeError,
    ClassificationError,
    DestructiveActionBlockedError,
    SafetyViolationError,
    QuarantineRequiredError,
    CleanupPlanError,
    AlreadyCleanedError,
)

__all__ = [
    # Models
    "AuditTarget",
    "DiskFinding",
    "ProjectFinding",
    "DockerFinding",
    "CleanupCandidate",
    "ComputerOpsReport",
    # Target constants
    "TARGET_DISK",
    "TARGET_PROJECT",
    "TARGET_DOCKER",
    "TARGET_SYSTEM",
    "VALID_TARGETS",
    # Severity constants
    "SEVERITY_LOW",
    "SEVERITY_MEDIUM",
    "SEVERITY_HIGH",
    "SEVERITY_CRITICAL",
    "VALID_SEVERITIES",
    # Action constants
    "ACTION_QUARANTINE",
    "ACTION_ARCHIVE",
    "ACTION_DELETE",
    "ACTION_KEEP",
    "ACTION_REVIEW",
    "SAFE_ACTIONS",
    "DESTRUCTIVE_ACTIONS",
    "VALID_ACTIONS",
    # Status constants
    "STATUS_IDENTIFIED",
    "STATUS_CLASSIFIED",
    "STATUS_QUARANTINED",
    "VALID_STATUSES",
    # Report status constants
    "REPORT_DRAFT",
    "REPORT_FINAL",
    "REPORT_ARCHIVED",
    "VALID_REPORT_STATUSES",
    # Service
    "ComputerOpsPlanner",
    "AuditPlan",
    "ClassificationResult",
    "SafeCleanupPlan",
    "build_readonly_audit_plan",
    "classify_cleanup_candidate",
    "generate_safe_cleanup_plan",
    # Errors
    "ComputerOpsError",
    "AuditPlanError",
    "EmptyTargetListError",
    "InvalidTargetTypeError",
    "ClassificationError",
    "DestructiveActionBlockedError",
    "SafetyViolationError",
    "QuarantineRequiredError",
    "CleanupPlanError",
    "AlreadyCleanedError",
]
