"""P22 Capability Forge Real — test generator for scaffolded skills."""
from __future__ import annotations

from src.capability_forge_lite.models import CapabilityProposal
from src.capability_forge_real.scaffold import _slug, _class_name


def generate_test_content(proposal: CapabilityProposal) -> str:
    """Gera conteudo de teste para uma capability.

    Args:
        proposal: CapabilityProposal aprovada

    Returns:
        String com conteudo do arquivo de teste
    """
    class_name = _class_name(proposal.capability_name)
    slug = _slug(proposal.capability_name)
    module_path = f"src.skills.{slug}.run"

    lines = [
        f'"""Tests for {proposal.capability_name} — auto-generated by P22 Capability Forge."""',
        "from __future__ import annotations",
        "",
        "import json",
        "import pytest",
        "",
        f"from {module_path} import run, {class_name}Input, {class_name}Output, _now_iso",
        "",
        "",
        f"class Test{class_name}:",
        f'    """Tests for {class_name} skill."""',
        "",
        "    def test_run_returns_dict(self):",
        f'        result = run({{"request": "test", "dry_run": True}})',
        "        assert isinstance(result, dict)",
        "",
        "    def test_run_has_status(self):",
        f'        result = run({{"request": "test", "dry_run": True}})',
        "        assert result.get(\"status\") == \"ok\"",
        "",
        "    def test_run_has_result(self):",
        f'        result = run({{"request": "test", "dry_run": True}})',
        '        assert "result" in result',
        "",
        f"    def test_{slug}_stub_message(self):",
        f'        result = run({{"request": "hello", "dry_run": True}})',
        f'        assert "{slug}" in result["result"]["message"]',
        "",
        "",
        f"class Test{class_name}Input:",
        f'    """Tests for {class_name}Input model."""',
        "",
        "    def test_defaults(self):",
        f'        inp = {class_name}Input(request="test")',
        "        assert inp.dry_run is True",
        "        assert inp.request == \"test\"",
        "",
        "    def test_to_dict(self):",
        f'        inp = {class_name}Input(request="test", dry_run=False)',
        "        data = inp.to_dict()",
        '        assert data["request"] == "test"',
        "        assert data[\"dry_run\"] is False",
        "",
        "",
        f"class Test{class_name}Output:",
        f'    """Tests for {class_name}Output model."""',
        "",
        "    def test_default_status(self):",
        f'        out = {class_name}Output(result={{}})',
        '        assert out.status == "ok"',
        "",
        "    def test_to_dict(self):",
        f'        out = {class_name}Output(result={{"key": "val"}}, status="ok")',
        "        data = out.to_dict()",
        '        assert data["result"] == {"key": "val"}',
        '        assert data["status"] == "ok"',
        "",
        "",
        "class TestNowIso:",
        "    def test_format(self):",
        "        ts = _now_iso()",
        '        assert "T" in ts',
        '        assert ts.endswith("Z")',
        "",
    ]

    return "\n".join(lines) + "\n"


def count_test_functions(test_content: str) -> int:
    """Conta funcoes de teste em um arquivo de teste.

    Args:
        test_content: Conteudo do arquivo de teste

    Returns:
        Numero de funcoes de teste (prefixo test_)
    """
    count = 0
    for line in test_content.split("\n"):
        stripped = line.strip()
        if stripped.startswith("def test_"):
            count += 1
    return count
