"""P13 Analytics/BI — local exporters (JSON, Markdown).

Zero network. Zero Docker. File-system only.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from src.analytics.errors import ExportError
from src.analytics.models import DashboardSpec, ReportSpec


# ═══════════════════════════════════════════════════════════════
# Dashboard JSON exporter
# ═══════════════════════════════════════════════════════════════

def export_dashboard_json(spec: DashboardSpec, path: str | Path) -> Path:
    """Export a DashboardSpec as a JSON file. Returns the output path."""
    try:
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "meta": {
                "exporter": "P13 Analytics/BI",
                "version": "1.0.0",
                "dry_run": True,
            },
            "dashboard": spec.to_dict(),
        }
        p.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
        return p.resolve()
    except (OSError, IOError) as exc:
        raise ExportError(f"Failed to export dashboard JSON to {path}: {exc}") from exc


# ═══════════════════════════════════════════════════════════════
# Report Markdown exporter
# ═══════════════════════════════════════════════════════════════

def export_report_markdown(spec: ReportSpec, path: str | Path) -> Path:
    """Export a ReportSpec as a Markdown file. Returns the output path."""
    try:
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)

        lines: list[str] = []
        lines.append(f"# {spec.title}")
        lines.append("")
        lines.append(f"> {spec.description}")
        lines.append("")
        lines.append(f"**ID:** `{spec.id}`")
        lines.append(f"**Format:** {spec.format}")
        lines.append(f"**Created:** {spec.created_at}")
        lines.append(f"**Mode:** dry-run (P13 Analytics/BI Skeleton)")
        lines.append("")

        if spec.sections:
            lines.append("---")
            lines.append("")
            for i, section in enumerate(spec.sections, 1):
                section_title = section.get("title", f"Section {i}")
                section_type = section.get("type", "text")
                section_content = section.get("content", "")

                lines.append(f"## {section_title}")
                lines.append("")
                lines.append(f"_Type: {section_type}_")
                lines.append("")

                if isinstance(section_content, str):
                    lines.append(section_content)
                elif isinstance(section_content, list):
                    for item in section_content:
                        lines.append(f"- {item}")
                lines.append("")

                charts = section.get("charts", [])
                if charts:
                    lines.append("### Charts")
                    lines.append("")
                    for chart in charts:
                        lines.append(
                            f"- **{chart.get('title', 'Chart')}** "
                            f"(`{chart.get('type', 'unknown')}`) — "
                            f"metric: `{chart.get('metric_id', '?')}`"
                        )
                    lines.append("")

            lines.append("---")
            lines.append("")
            lines.append(
                "_Generated by P13 Analytics/BI Skeleton — deterministic, dry-run, zero-network._"
            )

        p.write_text("\n".join(lines), encoding="utf-8")
        return p.resolve()
    except (OSError, IOError) as exc:
        raise ExportError(f"Failed to export report markdown to {path}: {exc}") from exc
